backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
publish_mode: editorial_workflow


media_folder: website/static/images
public_folder: /images

site_url: https://oldtheater.org
display_url: https://oldtheater.org

collections:
  # Category: HOME PAGE. Section: Show list.
  # - name: 'shows' # Used in routes, e.g., /admin/collections/blog
  #   label: 'Shows' # Used in the UI
  #   folder: 'website/content/shows' # The path to the folder where the documents are stored
  #   create: true # Allow users to create new documents in this collection
  #   slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
  #   fields: # The fields for each document, usually in front matter
  #     - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog'}
  #     - {label: 'Title', name: 'title', widget: 'string'}
  #     - {label: 'Event Date / Time', name: 'date', widget: 'datetime', hint: 'Please select the event Date and Time (At bottom of picker)'}
  #     - {label: 'Price', name: 'price', widget: 'string' }
  #     - {label: 'Location', name: 'location', widget: 'string' }
  #     - {label: 'Location Detail', name: 'locationDetail', widget: 'string', required: false }
  #     - {
  #         label: 'Show Type',
  #         name: 'showtype',
  #         widget: 'select',
  #         options: [{ label: 'FLICK', value: 'FLICK' }, { label: 'FRIDAY FLICK', value: 'FRIDAY FLICK' },{ label: 'SATURDAY FLICK', value: 'SATURDAY FLICK' }, { label: 'LIVE MUSIC', value: 'LIVE MUSIC' }, { label: 'LIVE THEATER', value: 'LIVE THEATER' }],
  #       }
  #     - {label: 'Short Description', name: 'shortDesc', widget: 'text' }
  #     - {label: 'Ticket Url', name: 'ticketUrl', widget: 'string', required: false  }
  #     - {label: 'Featured Image', name: 'img', widget: 'image', choose_url: false,  required: false }
  #     - {label: 'Image Description', name: 'imgAlt', widget: 'string', required: false }
  #     - {label: 'YouTube Video Id', name: 'youtubeVideo', widget: 'string', required: false  }
  #     - {label: 'Body', name: 'body', widget: 'markdown'}

  # ABOUT US ########################################################
  # Category ABOUTS. Pages: Editor Can not create or delete
  - name: 'abouts' # Used in routes, e.g., /admin/collections/blog
    label: 'About Us' # Used in the UI
    folder: 'website/content/abouts' # The path to the folder where the documents are stored
    media_folder: '/website/static/images/about'
    public_folder: '/images/about'
    create: false # Allow users to create new documents in this collection
    delete: false # prevent users from deleting files in this collection
    fields: # The fields for each document, usually in front matter
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog'}
      - {label: 'Folder', name: 'folder', widget: 'hidden', default: '/about/'}
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Body', name: 'body', widget: 'markdown'}
      - label: Body Image 
        name: body-image
        widget: image
        required: false
        choose_url: false
        default: ""
        hint: "Upload an image that you want to display in this page (optional). There are two ways to display an image on the page after you have uploaded it. **FIRST WAY: Use the Rich Text Editor.** Select 'Rich Text' in the toolbar above. In the toolbar, click the '+' and choose 'image'. In the Image widget, select the image wish to display.  **SECOND WAY: Add Markdown Code to the Page.** Select 'Markdown' in the toolbar above. Add this code to page: `![image description](/images/about/my-image-file.jpg)`. Replace the text 'my-image-file.jpg' with the name of the image you wish to display." 
      - label: "PDF Upload"
        name: "manual_pdf"
        widget: "file"
        required: false
        media_folder: '/website/static/pdf'
        choose_url: false
        hint: "Upload a .pdf file that you want to link to in this page (optional). To display a link to your pdf file, Select 'Markdown' in the toolbar above. Add this code to page: `[Link text to display](../pdf/my-file.pdf)`. Replace the text 'my-file.pdf' with the name of the pdf you wish to link to." 
        media_library:
          config:
            multiple: true
      


    # Category: ABOUT US, Page: About US: image gallery at bottom of page
  - label: "About Us page: Image gallery"
    title: Images for image gallery at bottom of the About Us page
    hint: this is a hint!
    name: "about-us-image-gallery"
    media_folder: '/website/static/images/about/galleryabout'
    public_folder: '/images/about/galleryabout'
    files:
      - label: "About Us page: Image gallery at bottom of page"
        name: "photos"
        file: "website/content/data/about/theater-photos.json"
        fields:
          - label: About Us page - Image gallery at bottom of page
            label_singular: Image
            name: photos
            widget: list
            fields:
              - {label: Image description, name: alt, widget: string, required: true, hint: description of image}
              - {label: Photo, name: img, widget: image, required: true, choose_url: false, default: "", hint: "NOTE: All photos in this gallery must be of exactly the same dimensions. Otherwise the photos will not display in tidy rows. Gallery was built with images at 910 x 683"}


    # Category: ABOUT US, Page: About/Board of Directors. Also supplies data for board widget on home page
  - label: "About Us: Board of Directors page"
    name: "board-of-directors"
    media_folder: '/website/static/images/board'
    public_folder: '/images/board'
    files:
      - label: "Executive Officers"
        name: "executive-officers"
        file: "website/content/data/board/executive-officers.json"
        fields:
          - label: Executive Officers
            label_singular: Executive Officer
            name: team
            widget: list
            fields:
              - {label: Role, name: role, widget: string, required: true}
              - {label: Name, name: name, widget: string, required: true, default: Open}
              - {label: Photo, name: img, widget: image, required: false, choose_url: false, default: "", hint: "NOTE: Photo must be square. Ideal photo size: 400 x 400 pixels"}
        
      - label: "Department Managers"
        name: "department-managers"
        file: "website/content/data/board/department-managers.json"
        fields:
          - label: Department Managers
            label_singular: Department Manager
            name: team
            widget: list
            fields:
              - {label: Role, name: role, widget: string, required: true}
              - {label: Name, name: name, widget: string, required: true, default: Open}
              - {label: Photo, name: img, widget: image, required: false, choose_url: false, default: "", hint: "NOTE: Photo must be square. Ideal photo size: 400 x 400 pixels"}
                  

  # # Category NEWS: Pages: Editor Can Create
  # - name: 'news' # Used in routes, e.g., /admin/collections/blog
  #   label: 'News' # Used in the UI
  #   folder: 'website/content/news' # The path to the folder where the documents are stored
  #   create: true # Allow users to create new documents in this collection
  #   fields: # The fields for each document, usually in front matter
  #     - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog' }
  #     - { label: 'Folder', name: 'folder', widget: 'hidden', default: '/news/' }
  #     - { label: 'Title', name: 'title', widget: 'string'}
  #     - { label: 'News Item Date', name: 'date', widget: 'datetime', hint: 'Please select the Date of this news item' }
  #     - { label: 'Summary', name: 'subhead', widget: 'string', required: true, hint: 'Please enter a short summary of this event' }
  #     - { label: 'Featured Image', name: 'img', widget: 'image', choose_url: false, required: false }
  #     - { label: 'Image Description', name: 'imgAlt', widget: 'string', required: false }
  #     - { label: 'Body', name: 'body', widget: 'markdown'}

      

  # Category:  FUNDRAISERS. Pages: Editor Can Create
  # - name: 'fundraisers'
  #   label: 'Fundraisers'
  #   media_folder: '/website/static/images/fundraisers/{{year}}'
  #   public_folder: '/images/fundraisers/{{year}}'
  #   folder: '/website/content/fundraisers'
  #   create: true
  #   format: 'frontmatter'
  #   slug: '{{slug}}'
  #   # editor:
  #   #   preview: true
  #   fields:
  #     - { label: 'Title', name: 'title', widget: 'string', required: true }
  #     - { label: 'Event Date', name: 'date', widget: 'datetime', hint: 'Please select the event Date'}
  #     - { label: 'Summary', name: 'summary', widget: 'string', required: false }
  #     - { label: 'Cover Image', name: 'img', widget: 'image', choose_url: false, required: false, allow_multiple: false }
  #     - { label: 'Cover Image Alt Text', name: 'alt', widget: 'string', required: false }
  #     - { label: 'Cover Image Caption', name: 'caption', widget: 'string', required: false }
  #     - { label: 'Body', name: 'body', widget: 'markdown', required: false }
  #     - {label: 'Folder', name: 'folder', widget: 'hidden', default: '/support/fundraisers/'}
  #     - label: "Image Gallery"
  #       name: "img_gallery"
  #       widget: "list"
  #       fields:
  #         - label: Image
  #           name: image
  #           widget: object
  #           fields:
  #             - {label: Image Headline, name: headline, widget: string, required: false }
  #             - {label: Image description, name: alt, widget: string}
  #             - {label: Image Caption, name: caption, widget: string, required: false}
  #             - {label: Image, name: img, widget: image , choose_url: false}


