backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
# publish_mode: editorial_workflow


media_folder: website/static/images
public_folder: /images

site_url: https://old-theater.netlify.app
display_url: https://old-theater.netlify.app

collections:
  - name: 'shows' # Used in routes, e.g., /admin/collections/blog
    label: 'Shows' # Used in the UI
    folder: 'website/content/shows' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog'}
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Event Date / Time', name: 'date', widget: 'datetime', hint: 'Please select the event Date and Time (At bottom of picker)'}
      - {label: 'Price', name: 'price', widget: 'string' }
      - {label: 'Location', name: 'location', widget: 'string' }
      - {label: 'Location Detail', name: 'locationDetail', widget: 'string', required: false }
      - {
          label: 'Show Type',
          name: 'showtype',
          widget: 'select',
          options: [{ label: 'FLICK', value: 'FLICK' }, { label: 'FRIDAY FLICK', value: 'FRIDAY FLICK' },{ label: 'SATURDAY FLICK', value: 'SATURDAY FLICK' }, { label: 'LIVE MUSIC', value: 'LIVE MUSIC' }, { label: 'LIVE THEATER', value: 'LIVE THEATER' }],
        }
      - {label: 'Short Description', name: 'shortDesc', widget: 'text' }
      - {label: 'Ticket Url', name: 'ticketUrl', widget: 'string', required: false  }
      - {label: 'Featured Image', name: 'img', widget: 'image', required: false }
      - {label: 'Image Description', name: 'imgAlt', widget: 'string', required: false }
      - {label: 'YouTube Video Id', name: 'youtubeVideo', widget: 'string', required: false  }
      - {label: 'Body', name: 'body', widget: 'markdown'}

      