backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
# publish_mode: editorial_workflow


media_folder: website/static/images
public_folder: /images

site_url: https://old-theater.netlify.app
display_url: https://old-theater.netlify.app

collections:
  - name: 'shows' # Used in routes, e.g., /admin/collections/blog
    label: 'Shows' # Used in the UI
    folder: 'website/content/shows' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog'}
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Event Date / Time', name: 'date', widget: 'datetime', hint: 'Please select the event Date and Time (At bottom of picker)'}
      - {label: 'Price', name: 'price', widget: 'string' }
      - {label: 'Location', name: 'location', widget: 'string' }
      - {label: 'Location Detail', name: 'locationDetail', widget: 'string', required: false }
      - {
          label: 'Show Type',
          name: 'showtype',
          widget: 'select',
          options: [{ label: 'FLICK', value: 'FLICK' }, { label: 'FRIDAY FLICK', value: 'FRIDAY FLICK' },{ label: 'SATURDAY FLICK', value: 'SATURDAY FLICK' }, { label: 'LIVE MUSIC', value: 'LIVE MUSIC' }, { label: 'LIVE THEATER', value: 'LIVE THEATER' }],
        }
      - {label: 'Short Description', name: 'shortDesc', widget: 'text' }
      - {label: 'Ticket Url', name: 'ticketUrl', widget: 'string', required: false  }
      - {label: 'Featured Image', name: 'img', widget: 'image', required: false }
      - {label: 'Image Description', name: 'imgAlt', widget: 'string', required: false }
      - {label: 'YouTube Video Id', name: 'youtubeVideo', widget: 'string', required: false  }
      - {label: 'Body', name: 'body', widget: 'markdown'}
  - name: 'fundraisers'
    label: 'Fundraisers'
    media_folder: '/website/static/images/fundraisers/{{year}}'
    public_folder: '/images/fundraisers/{{year}}'
    folder: '/website/content/fundraisers'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    # editor:
    #   preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Event Date', name: 'date', widget: 'datetime', hint: 'Please select the event Date'}
      - { label: 'Summary', name: 'summary', widget: 'string', required: false }
      - { label: 'Cover Image', name: 'img', widget: 'image', required: false, allow_multiple: false }
      - { label: 'Cover Image Alt Text', name: 'alt', widget: 'string', required: false }
      - { label: 'Cover Image Caption', name: 'caption', widget: 'string', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }
      - {label: 'Folder', name: 'folder', widget: 'hidden', default: '/support/fundraisers/'}
      - {
        label: 'Gallery',
        name: 'gallery',
        widget: 'list',
        required: false,
        summary: '{{fields.image}}',
        field: { label: 'Image', name: 'image', widget: 'image' }
      }
      - label: "Image Gallery"
        name: "img_gallery"
        widget: "list"
        fields:
          - label: Image
            name: image
            widget: object
            fields:
              - {label: Image Headline, name: headline, widget: string, required: false }
              - {label: Image description, name: alt, widget: string}
              - {label: Image Caption, name: caption, widget: string, required: false}
              - {label: Image, name: img, widget: image}
      